all:
	pdflatex -jobname presRUS pres.tex
	pdflatex -jobname presRUS pres.tex
	pdflatex -jobname presENG pres.tex
	pdflatex -jobname presENG pres.tex
clean:
	rm -f *.aux pres.log *.nav *.out *.snm *.vrb *.toc
